### ISSUE TITLE
Problem with title location in Heatmap function

### ISSUE THREAD

**Issue by Jeromeg666** [DrJ001/ASMap#1]
Hi,

Sorry to disturb you with this question. I am trying to generate the heatmap with ASMap as the quality is better than R/QTL. I was successful at generating the map and it fits what I have generated previously with R/QTL. However, the title of the plot ''Pairwise recombination fraction and LOD scores'' is now located in the plot instead of being above it. When I generated the plot, I used the QTL objects so the mistake might come from there. 

I called this function and everything worked, except for the title:
heatMap(nameofmyobject, lmax = 50)

![image](https://github.com/DrJ001/ASMap/assets/77698646/b3122770-10ec-4ee7-ac6b-6a68e43e0eb1)

Thanks.

**Comment by DrJ001** [comment]
Agree .. its a really poorly placed title thats just using a bad default .. I suggest you override the title altogether by doing 

`heatMap(nameofmyobject, lmax = 50, main = "")`

--Julian

**Comment by Jeromeg666** [comment]
Thanks for your input. This is working now. Have a good day!

**Comment by Jeromeg666** [comment]
While we are at it, do you have a tip that would help me in saving this into an .svg file without having it being too large. The files for my linkage maps are about 14-45 Mb when I save them as a 18X18 .pdf file. I had the same issues with the PlotRF function in R/QTL. 

I would like to use those plots in publications, but each time I am finally using them as .png files. However, the resolution is not great for publication standards. My gut feeling is that there is no real option for me here since there is so much details in each of the plot, but I would like to hear you on that topic. 

Thank you.

**Comment by DrJ001** [comment]
The `heatMap()` function uses `image.plot()` from the fields package and this has an argument called `useRaster = TRUE` for quicker plotting on screen.  You can just use this argument in `heatMap()`.

Once you have done this you can just use 

`dev.print(png, filename = yourfilename, width = spec.width, height = spec.height, units = "inches", res = 600)`

Just adjust `spec.height` and `spec.width` to get aestheticaly what you want or altrnatively remove both dimensions and it will use the plot region from your device as the ratio you want. The `res = 600` will publication quality and also small enough to add to docs.

Hope this helps.

**Comment by Jeromeg666** [comment]
It truly helps. Thank you so much!
